__title__ = "pystone"
__version__ = "0.1.0"
__author__ = "Giovanni Salinas"
__author_email__ = "gbs3@protonmail.com"
__description__ = "A command line tool written in Python for translating text through Reverso."
__url__ = "https://github.com/GBS3/pystone"
__license__ = "MIT License"
__copyright__ = "Copyright 2021 Giovanni Salinas"
